// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hledaavuvlmsgqrfjudw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZWRhYXZ1dmxtc2dxcmZqdWR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTQ0MDksImV4cCI6MjA3MjAzMDQwOX0.g3tYmeHGwHw79ifKGg1sKdliXwwvgSxO_LCNOwEHoBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});